import Head from 'next/head';
import Navbar from '../components/Navbar/index';
import Banner from '../components/Banner/index';
import Companies from '../components/Companies/index';
import Work from '../components/Work/index';
import Table from '../components/Table/index';
import Features from '../components/Features/index';
import Simple from '../components/Simple/index';
import Trade from '../components/Trade/index';
import Faq from '../components/Faq/index';
import Footer from '../components/Footer/index';
import ContactForm from '@/components/Contact';

export default function Home() {
  return (
    <>
      <Head>
        <title>Eurosia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="fav.png" />
      </Head>
      <main>
       {/*  <Navbar /> */}
        <Banner title='Welcome to Eurosia ' description='We are a leading IT company that specializes in custom software development and digital solutions. Our team of experts can help you streamline your processes, improve your online presence, and boost your bottom line.' leftImage=''/>
        {/* <Companies /> */}
        <Work />
        {/* <Table /> */}
        <Features />
        <Simple />
        <Trade />
        {/* <ContactForm/> */}
        {/* <Faq /> */}
       
      </main>
    </>
  )
}
