import Head from 'next/head';
import Navbar from '../components/Navbar/index';
import Banner from '../components/Banner/index';
import Companies from '../components/Companies/index';
import Work from '../components/Work/index';
import Table from '../components/Table/index';
import Features from '../components/Features/index';
import Simple from '../components/Simple/index';
import Trade from '../components/Trade/index';
import Faq from '../components/Faq/index';
import Footer from '../components/Footer/index';
import ContactForm from '@/components/Contact';
import ThemeToggle from '../components/ThemeToggle'
export default function Home() {
  return (
    <>
      <Head>
        <title>Eurosia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="fav.png" />
      </Head>
      <main>
      
       {/*  <Navbar /> */}
        <Banner title='Welcome to Eurosia' description='Eurosia | ইউরোশিয়া , we strive to provide exceptional service and innovation across various sectors including Real Estate, Technologies, Restaurants, Hotels, Travel Agencies, Food, Home Appliances, Newspapers, and Agro-businesses. Our mission is to empower brand partners with a unified dashboard for seamless searching, comparing, and managing their operations. We are committed to delivering reliable solutions and enhancing efficiency in every aspect of our clients business ventures.' leftImage=''/>
        {/* <Companies /> */}
        <Work />
        {/* <Table /> */}
        <Features />
        <Simple />
        <Trade />
        {/* <ContactForm/> */}
        {/* <Faq /> */}
       
      </main>
    </>
  )
}
